const assert=require('node:assert/strict');
globalThis.crypto=require('node:crypto').webcrypto;
const core=require('../extension/core.js');
assert.equal(core.defaults.audio,'มีบทพูด');
const scenes=[{episode:1,shot:1,description:'มินพบธารที่ท่าน้ำ',dialogue:''},{episode:1,shot:2,description:'ธารตอบมิน',dialogue:''}];
const request=core.dialoguePrompt({...core.defaults,duration:5},scenes);
assert.ok(request.includes('10 วินาที'));assert.ok(request.includes('มินพบธารที่ท่าน้ำ'));
assert.throws(()=>core.dialoguePrompt(core.defaults,[{...scenes[0],description:''}]));
const answer={scenes:[{episode:1,shot:2,dialogue:'ธาร: ข้าสัญญา'},{episode:1,shot:1,dialogue:'มิน: เจ้าจะกลับมาไหม?'}]};
assert.deepEqual(core.parseDialogues(JSON.stringify(answer),scenes),['มิน: เจ้าจะกลับมาไหม?','ธาร: ข้าสัญญา']);
assert.throws(()=>core.parseDialogues(JSON.stringify({scenes:[answer.scenes[0],answer.scenes[0]]}),scenes));
assert.throws(()=>core.parseDialogues(JSON.stringify({scenes:[answer.scenes[0]]}),scenes));
assert.throws(()=>core.parseDialogues(JSON.stringify({scenes:scenes.map(s=>({...s,shot:s.shot+3}))}),scenes));
assert.throws(()=>core.parseDialogues(JSON.stringify({scenes}),scenes));
const prompt=core.prompt({...core.defaults,audio:'เสียงบรรยากาศ ไม่มีบทพูด'},{...scenes[0],dialogue:'มิน: เจ้าจะกลับมาไหม?'});
assert.ok(!prompt.includes('มิน: เจ้าจะกลับมาไหม?'));assert.ok(!prompt.includes('เสียงและปากสัมพันธ์กัน'));assert.ok(prompt.includes('เสียงบรรยากาศ ไม่มีบทพูด'));
const plot={title:'ท่าน้ำ',synopsis:'เรื่องรัก',characters:'มินและธาร',scenes};
assert.throws(()=>core.parsePlot(JSON.stringify(plot),{...core.defaults,episodes:1}),/ยังไม่มีบทพูด/);
assert.equal(core.parsePlot(JSON.stringify(plot),{...core.defaults,episodes:1,audio:'ไม่มีเสียง'}).scenes.length,2);
console.log('PASS: dialogue generation, scene matching, silent response rejection and spoken video prompts');
